services:
  - type: web
    name: foodfusion
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd 'Food Ordering' && gunicorn foodOrderSystem.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: foodfusion-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"

  - type: pserv
    name: foodfusion-db
    runtime: postgres
    plan: free