services:
  - type: web
    name: foodfusion
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd 'Food Ordering' && gunicorn foodOrderSystem.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: "3.12"

      - key: DJANGO_DEBUG
        value: "False"

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"