# Generated by Django 6.1.1 on 2026-09-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_fooditems_restaurantname"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantuser",
            name="ownerName",
            field=models.CharField(default="Unknown Owner", max_length=50),
            preserve_default=False,
        ),
    ]
